### ISSUE TITLE
Installation does not take into account symlinked runcom files

### ISSUE THREAD

**Issue by webpro** [withfig/config#42]
### Description

The installation broke my custom setup as I have [`.bashrc` and `.bash_profile` symlinked](https://github.com/webpro/dotfiles/blob/5ef14c3ec4d344e44489a0316a7645a8bf2f7548/Makefile#L42). After the installation I found the links were replaced with the actual target file contents (including the changes made by fig), so my own sourced files could not be found anymore.

### Details

|macOS|Fig|Shell|
|-|-|-|
|10.15.7|Version 1.0.47 (B257)|/usr/local/bin/bash|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Version 1.0.47 (B257) [ABC] 
UserShell: /usr/local/bin/bash
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/lars/.fig/bin/fig
Accessibility: true
Number of specs: 190
SSH Integration: false
Tmux Integration: true
Keybindings path: /Users/lars/.fig/user/keybindings
iTerm Integration: false 
Hyper Integration: false
VSCode Integration: true
Docker Integration: false
Symlinked dotfiles: true
Only insert on tab: false
Installation Script: false
PseudoTerminal Path: /Users/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/Wireshark.app/Contents/MacOS:/Users/lars/.fig/bin
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: ??? (???) - ???
Current working directory: ???
Current window identifier: 59633/% (com.microsoft.VSCode)</pre>
</p>
</details>

**Comment by mschrage** [comment]
Thanks for reporting this! I think this should be fixed in the next build: https://github.com/withfig/config/commit/37cf6f88781e75a0992708508b4815e4f5296bd6#diff-f9d35d43770d39092a663e665e82ae1d84a9e0da3d0d10c407acada6a40cd281
